### ISSUE TITLE
漫画话与卷混合时，文件的顺序问题

### ISSUE THREAD

**Issue by Kolakona** [chu-shen/BangumiKomga#1]
例如某一部漫画中包含的话与卷的文件名（纯数字的是连载话）：
016.zip
017.zip
018.zip
019.zip
020.zip
021.zip
022.zip
023.zip
024.zip
025.zip
Vol.01.zip
Vol.02.zip
Vol.03.zip

放在komga中入库扫描后文件顺序不会改变，运行本脚本后库中文件顺序变为：
1-016
1-Vol.01
2-017
2-Vol.02
3-018
3-Vol.03
4-019
5-020
6-021
7-022
8-023
9-024
10-025

**Comment by chu-shen** [comment]
## 文件序号逻辑

### 运行脚本前

运行脚本前komga中顺序如下：
![image](https://user-images.githubusercontent.com/45256288/217723983-4f1ed932-a587-4740-b1ce-e6cedaa21fa7.png)

_注意：komga并不是按照文件名中的序号进行排序的_

### 运行脚本后

运行脚本后komga中顺序如下：
![image](https://user-images.githubusercontent.com/45256288/217725540-ca447b5c-f8e8-423f-8b32-ca608002b64d.png)

红框中三本书匹配到元数据，并**更新序号**。其余书的**序号未变**

### 逻辑

本脚本目前将书籍系列下所有书均视为单行本/卷

在匹配单行本元数据时，会提取此系列下每本书的最后一个数字，与bangumi上单行本的序号进行比较：
- 如果序号一致，则刷新元数据，更新序号
- 如果序号不一致，则跳过此书

**Comment by Kolakona** [comment]
komga里的顺序和windows资源管理器中的文件顺序是一样的，也就是不只是看数字序号，还看前面的其他字符排序吧。

上文逻辑大抵明白了，就是原来只有016单话排序为1，脚本识别到卷1后更新该卷序号也为1，这样的意思吧。

理想情况是卷排序在前，连载话排序在后，这样komga也能识别到卷1单行本的封面。不过这可能需要在导入库之前就把文件名改为符合顺序的？毕竟脚本没有涉及到komga系列封面的处理。

总之感谢回复与脚本开发，看到todo中“区分单册和单话”了，期待更新！

**Comment by chu-shen** [comment]
> komga里的顺序和windows资源管理器中的文件顺序是一样的，也就是不只是看数字序号，还看前面的其他字符排序吧。
> 
> 上文逻辑大抵明白了，就是原来只有016单话排序为1，脚本识别到卷1后更新该卷序号也为1，这样的意思吧。
> 
> 理想情况是卷排序在前，连载话排序在后，这样komga也能识别到卷1单行本的封面。不过这可能需要在导入库之前就把文件名改为符合顺序的？毕竟脚本没有涉及到komga系列封面的处理。
> 
> 总之感谢回复与脚本开发，看到todo中“区分单册和单话”了，期待更新！

嗯，总之就是没有匹配到的就不会修改元数据。

`区分单册和单话`这个功能可能不会做🥲简化成：将未匹配的书重新排序
