### ISSUE TITLE
系列里面的单行本识别问题

### ISSUE THREAD

**Issue by anihao** [chu-shen/BangumiKomga#12]
小说系列识别成了漫画，使用cbl修改正确后，系列里面的单行本还是识别为漫画单行本，能否通过cbl修改正确（按照教程试了一下没反应）
![1](https://github.com/chu-shen/BangumiKomga/assets/111543417/80052628-8319-4017-8ac7-f5bd7a40be2b)
![2](https://github.com/chu-shen/BangumiKomga/assets/111543417/c8463a3a-ffe2-4861-a864-475d76c10700)
![3](https://github.com/chu-shen/BangumiKomga/assets/111543417/df7138dd-7485-4f7d-90c9-6961d487acc2)

**Comment by chu-shen** [comment]
`cbl`目前只针对系列有效，所以应该在系列中填写，而不是在具体某本中填写，也就是不能在图2中填写

填写`cbl`后会[强制刷新此系列所有元数据](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%AD%A3%E9%94%99%E8%AF%AF%E5%85%83%E6%95%B0%E6%8D%AE)，包括单行本，所以程序是必定执行了的，你可以看下日志`refreshMetadata.log`

---

86 这个系列是所有单行本都出现这个问题了吗？

Bangumi 上 86 第一本没带序号，导致第一本匹配不到数据，所以日志中应该会提示更新失败

**Comment by anihao** [comment]
明白了，细看了下只有第一本有问题
