### ISSUE TITLE
希望加入单行本封面也使用bangumi缩略图的设置

### ISSUE THREAD

**Issue by oreme2** [chu-shen/BangumiKomga#13]
注意到系列封面有使用bangumi缩略图的设置，当未自行上传海报时。
bangumi对系列单行本也设有缩略图；为保持一致，是否可以加入单行本封面也使用bangumi缩略图的设置选项

**Comment by oreme2** [comment]
另外可以重新刮削FAILED_SERIES，但是如何重新刮削指定的successful_SERIEs?
比如我发现成功刮削一部漫画但识别错误之后重新改了名，但是我再刮削时直接跳过.
当然可以删除.db文件，但这样是重新刮削所有漫画ALL_SERIES,而不是指定的successful_SERIEs

**Comment by oreme2** [comment]
最后，可以设置黑名单么。有的漫画自带我手动上传的元数据，我不希望用bangumi刮削，这样会直接覆盖，而不是跳过。
现在要实现黑名单只能将手动上传元数据的SERIES设置新库，然后只刮削旧库。。。。

**Comment by chu-shen** [comment]
> 另外可以重新刮削FAILED_SERIES，但是如何重新刮削指定的successful_SERIEs? 比如我发现成功刮削一部漫画但识别错误之后重新改了名，或者我设置不再使用bangumi缩略图作为系列封面，但是我再刮削时直接跳过. 当然可以删除.db文件，但这样是重新刮削所有漫画ALL_SERIES,而不是指定的successful_SERIEs

详见：[系列元数据更新错误，即匹配错误](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%AD%A3%E9%94%99%E8%AF%AF%E5%85%83%E6%95%B0%E6%8D%AE)

**Comment by oreme2** [comment]
> > 另外可以重新刮削FAILED_SERIES，但是如何重新刮削指定的successful_SERIEs? 比如我发现成功刮削一部漫画但识别错误之后重新改了名，或者我设置不再使用bangumi缩略图作为系列封面，但是我再刮削时直接跳过. 当然可以删除.db文件，但这样是重新刮削所有漫画ALL_SERIES,而不是指定的successful_SERIEs
> 
> 详见：[系列元数据更新错误，即匹配错误](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%AD%A3%E9%94%99%E8%AF%AF%E5%85%83%E6%95%B0%E6%8D%AE)
好的，是我没有仔细看了
