### ISSUE TITLE
如何通过docker使用该脚本

### ISSUE THREAD

**Issue by Profitter** [chu-shen/BangumiKomga#15]
rt
已在运行komga的服务器上创建好了bangumikomga容器，已经配置好了config.py
请问下一步在哪里运行 python refreshMetadata.py
（本人小白请见谅）

**Comment by chu-shen** [comment]
启动这个容器就会自动运行`python refreshMetadata.py`，执行完会自动关闭

然后点击这个容器就可以看到相应日志。如果配置了`refreshMetadata.log`，则查看这个文件

---

题外话，如果想要定时自动执行，可以搭配其他工具，比如[ofelia](https://github.com/mcuadros/ofelia)

**Comment by Profitter** [comment]
谢谢大佬，在同局域网的win和服务器的docker上都运行成功了，但是log文件显示2024-10-12 14:32:22,726 - root - INFO - refreshMetadata.py : 147 - Finish! succeed: 0, failed: 0，config.py中填写的komga库中的漫画元数据也没有变化，已经提前添加了cbl标签，请问是我哪里设置有误导致未刮削到bgm.tv的元数据呢

**Comment by Profitter** [comment]
补充：
在关闭代理，KOMGA_LIBRARY_LIST设为空，RECHECK_FAILED_SERIES设为True，FORCE_REFRESH_LIST填入已经设置好cbl的漫画系列后刮削成功

**Comment by chu-shen** [comment]
😂那应该没问题，用个新的库再试试

**Comment by Profitter** [comment]
有一个可行的办法就行，开代理时报错如下，可能从fq节点ip发出的请求数过多被bgm.tvban掉了也说不定，不开代理是ok的，从没想过还能是网络会出问题
2024-10-12 23:08:48,874 - urllib3.connectionpool - WARNING - connectionpool.py : 810 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /v0/subjects/35906

**Comment by chu-shen** [comment]
看你访问 bgm 啥情况，稳定就不用配置代理了，不稳定的话更新下订阅+换个节点
