### ISSUE TITLE
请求增加1项书库展示信息的优化功能

### ISSUE THREAD

**Issue by flamesky80** [chu-shen/BangumiKomga#17]
功能需求：将检索到的Vol.x 中的数字作为卷序号，而不是将最后一个数字当做卷序号

![image](https://github.com/user-attachments/assets/055da984-23cb-44a0-a5dc-f10b7cd46feb)
如上图，文件名的格式为 [漫画名][作者][出版社][卷序号][卷名称][出版日期].zip
BangumiKomga运行刮削之后，把出版日期当做序号来显示了。
经测试，这种显示的错误确实是脚本运行后显示的；如果停止整个Docker不运行脚本，让Komga的扫描书库，只会将文件的排序当做卷序号来用，不会显示1972这种年份数字。

如果把[卷序号]放到文件名的最后一段，可以解决该问题，但是在文件管理器中的排序就不对了，因为卷名称、出版日期等信息都可能被系统用来排序。
也不符合你的插件的命名建议规则。`[漫画名称][作者][出版社][卷数][其他1][其他2]`

**Comment by chu-shen** [comment]
已添加
