### ISSUE TITLE
修正错误元数据功能不生效

### ISSUE THREAD

**Issue by flamesky80** [chu-shen/BangumiKomga#18]
![image](https://github.com/user-attachments/assets/b58ac19f-a2fb-4c76-8fd3-8ca502ed64f8)
![image](https://github.com/user-attachments/assets/bc1d5557-ee27-4eb0-bd33-a839bba1ac44)

如上图，我按照readme里面的说明进行操作，但是没有效果，仍然获取到另外一部漫画的元数据。

> 如何修正错误元数据
> 人工修正错误元数据可以使用cbl(Correct Bangumi Link)，只需在系列元数据的链接中填入cbl和该漫画系列的 bangumi 地 址。此链接将在匹配时最先使用。
> 
> 下面分三种情况说明具体操作：
> 
> 自此系列添加至 komga 后还未运行过此程序：
> 
> 填入上面提到的信息
> 正常执行python refreshMetadata.py
> 系列元数据更新失败，即「标题」与「排序标题」一样：
> 
> 填入上面提到的信息
> 将RECHECK_FAILED_SERIES配置为True，重新匹配失败的系列
> 正常执行python refreshMetadata.py

**Comment by chu-shen** [comment]
哪一种情况操作的？

**Comment by chu-shen** [comment]
更新失败和更新错误不一样，看图是匹配到 bangumi 条目了，但是和本地书籍不一致，这属于更新错误

**Comment by flamesky80** [comment]
2种情况都试过了。
第一次是新增，发现找不到正确的元数据；然后就在git上看 cbl手动修正的方法，按方法操作，还是刮削不到。

**Comment by flamesky80** [comment]
再次测试。

将丁丁历险记的25本书都单独建目录存放，当做单行本。
目录结构为
> 埃尔热
>>>>丁丁在刚果
>>>>蓝莲花
>>>> ……

启动刮削脚本前，一半提前写入 cbl和bangumi链接，另外一半留空。
启动后，写入链接的成功获取数据，另外一半完全获取不到或者获取错误。

再将留空一半配置cbl和bangumi链接。
启动脚本，如果之前获取不到的，可以获取到，但是之前获取出错的仍然获取不到。

删掉获取出错的所有信息，在config.py中将 RECHECK_FAILED_BOOKS = True ，FORCE_REFRESH_LIST = [] 填入出错的单行本的Komga ID。
启动脚本，成功获取。

**Comment by chu-shen** [comment]
看描述没有问题。所以问题解决了？

**Comment by flamesky80** [comment]
请问有可能提升自动刮削的成功率吗？
如果每本漫画刮削前要cbl，刮削错了还要配置 config.py 的FORCE_REFRESH_LIST，属实有点费操作。

**Comment by chu-shen** [comment]
> 请问有可能提升自动刮削的首次正确率吗？ 如果每本漫画刮削前要先配置cbl和链接。 如果没有配置，没有刮削前也不知道哪一本能正确刮削到，哪一本不能，一旦刮削错了光是配置cbl+链接还不够，还要去配置FORCE_REFRESH_LIST，属实有点费操作。

错误率有多高？举些刮削错误的例子，不保证能修复

我目前使用还行，而且 Komga 中保留了原始标题，即使刮削错误也还是可以手动搜到的

cbl 这块确实比较乱，有空调整下

**Comment by flamesky80** [comment]
我这几天试用的效果，25本丁丁历险记，Komga扫描入库后，如果不手动配cbl，25本全都刮削不出来或者刮削错误，或者可能有1、2本能。
https://bgm.tv/subject/105716

**Comment by chu-shen** [comment]
> 我这几天试用的效果，25本丁丁历险记，Komga扫描入库后，如果不手动配cbl，25本全都刮削不出来或者刮削错误，或者可能有1、2本能。 https://bgm.tv/subject/105716

单行本匹配是根据文件序号来的，你这些都没有序号，自然匹配不到

除了这25本外呢

**Comment by flamesky80** [comment]
> > 我这几天试用的效果，25本丁丁历险记，Komga扫描入库后，如果不手动配cbl，25本全都刮削不出来或者刮削错误，或者可能有1、2本能。 https://bgm.tv/subject/105716
> 
> 单行本匹配是根据文件序号来的，你这些都没有序号，自然匹配不到
> 
> 除了这25本外呢

https://bgm.tv/subject/105714
请问，序号是这个 105714 吗？

**Comment by flamesky80** [comment]
> > 我这几天试用的效果，25本丁丁历险记，Komga扫描入库后，如果不手动配cbl，25本全都刮削不出来或者刮削错误，或者可能有1、2本能。 https://bgm.tv/subject/105716
> 
> 单行本匹配是根据文件序号来的，你这些都没有序号，自然匹配不到
> 
> 除了这25本外呢

我又继续试了一下，大部分单行本确实都有问题。看来只能手动刮削了。谢谢。

**Comment by chu-shen** [comment]
> > > 我这几天试用的效果，25本丁丁历险记，Komga扫描入库后，如果不手动配cbl，25本全都刮削不出来或者刮削错误，或者可能有1、2本能。 https://bgm.tv/subject/105716
> > 
> > 
> > 单行本匹配是根据文件序号来的，你这些都没有序号，自然匹配不到
> > 除了这25本外呢
> 
> https://bgm.tv/subject/105714 请问，序号是这个 105714 吗？

这个`[SLAM DUNK 完全版 (01)](https://bgm.tv/subject/9093)`，如果本地文件为1.zip，链接和本地都能提取出`1`，则刮削这本单行本

目前只是根据单行本里的序号数字来比对匹配的，并没有查询标题

**Comment by chu-shen** [comment]
> 请问有可能提升自动刮削的首次正确率吗？ 如果每本漫画刮削前要先配置cbl和链接。 如果没有配置，没有刮削前也不知道哪一本能正确刮削到，哪一本不能，一旦刮削错了光是配置cbl+链接还不够，还要去配置FORCE_REFRESH_LIST，属实有点费操作。

现在配置`cbl`后可以直接运行程序进行刮削

**Comment by flamesky80** [comment]
> > 请问有可能提升自动刮削的首次正确率吗？ 如果每本漫画刮削前要先配置cbl和链接。 如果没有配置，没有刮削前也不知道哪一本能正确刮削到，哪一本不能，一旦刮削错了光是配置cbl+链接还不够，还要去配置FORCE_REFRESH_LIST，属实有点费操作。
> 
> 现在配置`cbl`后可以直接运行程序进行刮削

经过测试，现在不用配置FORCE_REFRESH_LIST也能重新刮削之前出错的漫画了。厉害！
