### ISSUE TITLE
文件序号处理逻辑相关

### ISSUE THREAD

**Issue by Kolakona** [chu-shen/BangumiKomga#2]
和番剧剧集中也偶尔会有“.5”的中间话类似
文件名例如：
016
016.5
017
018

或：
016
016.5 番外1
017
017.5 番外2
018

如果脚本逻辑是提取文件名中最后一个数字则会导致顺序错误。
是否考虑当数字字符中夹杂一个标点符号如“.” "-" "_"也将其视为一个数字，或者其他的序号提取识别办法。

**Comment by chu-shen** [comment]
已更新
