### ISSUE TITLE
log重复提示connectionpool - WARNING

### ISSUE THREAD

**Issue by leohuno** [chu-shen/BangumiKomga#27]
- urllib3.connectionpool - WARNING - connectionpool.py : 873 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c4c056ed0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/login/set-cookie

重复在群晖上弄了两天还是相同问题，不是很清楚这个报错的类型

**Comment by chu-shen** [comment]
检查下容器的网络设置，容器与 komga 是否能连通

试下 docker compose 里添加：`    network_mode: host`

**Comment by leohuno** [comment]
很感谢你百忙之中抽出时间回答，根据你的提示问题已经解决啦。

但是具体细节是需要把BangumiKomga改成host，而且同时还要把Komga也要改成host才行
我原来的情况是BangumiKomga是host，Komga是bridge导致的
