### ISSUE TITLE
Docker immediately stopping after starting

### ISSUE THREAD

**Issue by anshul-rao** [chu-shen/BangumiKomga#28]
Hello, I have setup BangumiKomga up in docker connected to the Komga container using a docker bridge and I'm checking the logs and here is what it says:
```
2024-11-20 02:12:10,964 - root - INFO - refreshMetadata.py : 147 - Finish! succeed: 0, failed: 0
2024-11-20 02:12:11,646 - root - INFO - refreshMetadata.py : 147 - Finish! succeed: 0, failed: 0
2024-11-20 02:12:12,384 - root - INFO - refreshMetadata.py : 147 - Finish! succeed: 0, failed: 0
2024-11-20 02:12:13,304 - root - INFO - refreshMetadata.py : 147 - Finish! succeed: 0, failed: 0
```

In the Komga server settings, it shows that BangumiKomga is logging in as well but no scraping is being done. Here is my config.py:
```
BANGUMI_ACCESS_TOKEN = ''
KOMGA_BASE_URL = "http://komga:25600"
KOMGA_EMAIL = "redacted"
KOMGA_EMAIL_PASSWORD = "redacted"
KOMGA_LIBRARY_LIST = ['0HY9J40RKJM86']
KOMGA_COLLECTION_LIST = []

RECHECK_FAILED_SERIES = False
RECHECK_FAILED_BOOKS = False

CREATE_FAILED_COLLECTION = False

# support 'GOTIFY', 'WEBHOOK', 'HEALTHCHECKS'
NOTIF_TYPE_ENABLE = []

NOTIF_GOTIFY_ENDPOINT = "http://IP:PORT"
NOTIF_GOTIFY_TOKEN = "TOKEN"
NOTIF_GOTIFY_PRIORITY = 1
NOTIF_GOTIFY_TIMEOUT = 10

NOTIF_WEBHOOK_ENDPOINT = "http://IP:PORT"
NOTIF_WEBHOOK_METHOD = "POST"
NOTIF_WEBHOOK_HEADER = {"Content-Type": "application/json"}
NOTIF_WEBHOOK_TIMEOUT = 10

NOTIF_HEALTHCHECKS_ENDPOINT = "http://IP:PORT"
NOTIF_HEALTHCHECKS_TIMEOUT = 10


# Poster
USE_BANGUMI_THUMBNAIL=False
USE_BANGUMI_THUMBNAIL_FOR_BOOK=False
```
How do I fix it so it can scrape the metadata? Also, will the metadata scraped be in Chinese or is it possible to scrape it in English as well?

**Comment by chu-shen** [comment]
1. try set `RECHECK_FAILED_SERIES = True` and rerun docker
2. Docker will automatically stop after execution. If you want to schedule automatic execution, you can pair it with other tools such as [ofelia](https://github.com/mcuadros/ofelia)
3. check if you can access `https://bgm.tv/`

---

[Bangumi](https://bgm.tv/) only supports Chinese.

If you need English metadata, you can check `https://github.com/Pfuenzle/AnisearchKomga`

**Comment by anshul-rao** [comment]
Thanks for the help! Unfortunately, the other repository is broken and I prefer English metadata. However, I appreciate your quick response!
