### ISSUE TITLE
执行 `python refreshMetadata.py` 报错

### ISSUE THREAD

**Issue by lb-fes** [chu-shen/BangumiKomga#5]
python refreshMetadata.py 后提示：

```
Traceback (most recent call last):
  File "d:\GitHub\BangumiKomga\refreshMetadata.py", line 268, in <module>
    refresh_metadata(FORCE_REFRESH_LIST)
  File "d:\GitHub\BangumiKomga\refreshMetadata.py", line 16, in refresh_metadata
    env = InitEnv()
          ^^^^^^^^^
  File "d:\GitHub\BangumiKomga\tools\env.py", line 21, in __init__
    self.komga.get_series_with_libaryid(library)['content'])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

refreshMetadata.log

```
2023-07-17 17:42:52,989 - root - ERROR - komgaApi.py : 33 - An error occurred: 502 Server Error: Bad Gateway for url: http://127.0.0.1:25600/api/v1/series?library_id=0D07507Y8X4SX&size=50000
```

python 3.11.4
windows 10

**Comment by chu-shen** [comment]
检查下：
- `library_id`是否正确
- komga IP 及端口是否正确

脚本是在 windows 上执行的吗？在浏览器直接访问看是否有数据返回：`http://127.0.0.1:25600/api/v1/series?library_id=0D07507Y8X4SX&size=50000`

**Comment by lb-fes** [comment]
都正确，在Windows上

返回数据如下：

```
{"content":[],"pageable":{"sort":{"empty":true,"sorted":false,"unsorted":true},"offset":0,"pageNumber":0,"pageSize":2000,"paged":true,"unpaged":false},"last":true,"totalPages":0,"totalElements":0,"size":2000,"number":0,"sort":{"empty":true,"sorted":false,"unsorted":true},"first":true,"numberOfElements":0,"empty":true}
```

**Comment by lb-fes** [comment]
> * 正确的值`0B79YYABE9EAV`，对应地址：`http://IP:PORT/libraries/0B79YYABE9EAV/series`
> * 错误的值`0D021T9SGWPTJ`，对应地址：`http://IP:PORT/series/0D021T9SGWPTJ`

库 Id 填错了，还有就是代理软件不知道为啥把 `127.0.0.1:25600` 给代理了，
感谢您的解答~♪(･ω･)ﾉ

**Comment by QIanyi-NK** [comment]
您好我也出现了运行脚本报错的问题

报错信息类似:
`  File "C:\Users\lenovo\Desktop\BangumiKomga-0.4.0\refreshMetadata.py", line 268, in <module>
    refresh_metadata(FORCE_REFRESH_LIST)
  File "C:\Users\lenovo\Desktop\BangumiKomga-0.4.0\refreshMetadata.py", line 16, in refresh_metadata
    env = InitEnv()
          ^^^^^^^^^
  File "C:\Users\lenovo\Desktop\BangumiKomga-0.4.0\tools\env.py", line 21, in __init__
    self.komga.get_series_with_libaryid(library)['content'])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str`

日志文件不同，返回的错误码为400:
`2024-01-27 10:17:54,692 - root - ERROR - komgaApi.py : 33 - An error occurred: 400 Client Error:  for url: http://127.0.0.1:25600//api/v1/series?library_id=0EYKW028BSCFG&size=50000`

python：3.11.5
windows11

库id与端口已确认无误，访问日志文件中的链接后出现以下界面
![QQ截图20240127102320](https://github.com/chu-shen/BangumiKomga/assets/74846176/d3176e6e-e56d-4401-b348-c3baf057044b)

**Comment by chu-shen** [comment]
> 日志文件不同，返回的错误码为400: `2024-01-27 10:17:54,692 - root - ERROR - komgaApi.py : 33 - An error occurred: 400 Client Error: for url: http://127.0.0.1:25600//api/v1/series?library_id=0EYKW028BSCFG&size=50000`
> 
> python：3.11.5 windows11
> 
> 库id与端口已确认无误，访问日志文件中的链接后出现以下界面 ![QQ截图20240127102320](https://private-user-

`http://127.0.0.1:25600//api/v1/series?library_id=0EYKW028BSCFG&size=50000`，这个地址`api`前面多了个`/`

**Comment by QIanyi-NK** [comment]
> > 日志文件不同，返回的错误码为400: `2024-01-27 10:17:54,692 - root - ERROR - komgaApi.py : 33 - An error occurred: 400 Client Error: for url: http://127.0.0.1:25600//api/v1/series?library_id=0EYKW028BSCFG&size=50000`
> > python：3.11.5 windows11
> > 库id与端口已确认无误，访问日志文件中的链接后出现以下界面 ![QQ截图20240127102320](https://private-user-
> 
> `http://127.0.0.1:25600//api/v1/series?library_id=0EYKW028BSCFG&size=50000`，这个地址`api`前面多了个`/`
> 
> 配置文件里是不是端口号后面多了个`/`

是的（是我铸币），改过之后好了。感谢大佬解答~♪(･ω･)ﾉ

**Comment by wolfling45** [comment]
我也出现了脚本执行错误的问题
`Traceback (most recent call last):
  File "refreshMetadata.py", line 268, in <module>
    refresh_metadata(FORCE_REFRESH_LIST)
  File "refreshMetadata.py", line 91, in refresh_metadata
    komga_metadata = processMetadata.setKomangaSeriesMetadata(
  File "C:\Users\wolfl\gitku\BangumiKomga\processMetadata.py", line 182, in setKomangaSeriesMetadata
    subjectRelations = bgm.get_related_subjects(bangumiMetadata['id'])
TypeError: list indices must be integers or slices, not str`

不过我的貌似是bgv库的问题
`2024-02-25 11:16:47,396 - root - ERROR - bangumiApi.py : 121 - An error occurred: 404 Client Error: Not Found for url: https://api.bgm.tv/v0/subjects/128817`

我也不知道这是哪本书，有没有办法跳过指定书籍的识别?

**Comment by chu-shen** [comment]
如果不是相同报错请直接开一个 issue

---

> 我也不知道这是哪本书，有没有办法跳过指定书籍的识别?

出错的是这本：`https://bgm.tv/subject/128817` （`钢铁神兵B'T-X`）

原因是有人添加了这个标签：`成年コミック `，脚本需要配置`BANGUMI_ACCESS_TOKEN`才能处理

---

执行失败后应该不会再次识别

如果需要识别正确，请按照[指示操作](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%AD%A3%E9%94%99%E8%AF%AF%E5%85%83%E6%95%B0%E6%8D%AE)
