### ISSUE TITLE
和tachiyomiJ2K komaga插件联动碰到no chapters found

### ISSUE THREAD

**Issue by qingmuhy** [chu-shen/BangumiKomga#8]
漫画元数据被更改后，tachij2k komaga就在中消失，表现为如下情况。

https://pan.qingmuhy.com:7002/s/FQqzagyrn3kfCrG

如果不修改元数据则可以正常显示

![image](https://github.com/chu-shen/BangumiKomga/assets/25658951/145fe2f6-ccc2-4b80-a127-7824cc42eda9)

22卷没有更改元数据，在安卓app中正常显示。

搜了很多资料，没有排错思路了，发在这全当是讨论了，因为感觉这个bug很奇怪。

**Comment by qingmuhy** [comment]
![1715610138853_d](https://github.com/chu-shen/BangumiKomga/assets/25658951/c743077a-bef6-4f33-8598-6094887785c2)

22话直接加入扫描未改动，在app 中正常显示。

**Comment by qingmuhy** [comment]
经过一晚上不断的销毁重建，发现这些不识别已经跟文件高度相关了。

这些文件都不能识别，但在搜刮元数据前是可以识别的，不知道问题出现在哪。

文件样本如下：https://pan.qingmuhy.com:7002/s/yHGifYfad4gfXex

**Comment by chu-shen** [comment]
> 经过检查啊，10-15元数据未被修改，但是在安卓app中也不可显示。

数据来自[BGM](https://bgm.tv/subject/218102)，目前只到第八本。

由于之后的没有数据，所以只会更新序号，因此才会出现下面警告：`Failed to update book: 9.别当欧尼酱了, Only update book number`


---
 
> 这些文件都不能识别，但在搜刮元数据前是可以识别的，不知道问题出现在哪。

你给的这个文件是`epub`格式，是不是 tachiyomiJ2K 本来就不支持？

---

从你给的第一个视频来看，不太像 Komga 和本工具的问题

tachiyomiJ2K 和 Komga 都是最新版本吗？

没用过 tachiyomiJ2K，试下其他工具有没有相同的问题，比如 https://github.com/mihonapp/mihon

**Comment by qingmuhy** [comment]
`由于之后的没有数据，所以只会更新序号，因此才会出现下面警告：Failed to update book: 9.别当欧尼酱了, Only update book number`

这个问题通过您的文档，我已经理解，的确没有问题。

`你给的这个文件是epub格式，是不是 tachiyomiJ2K 本来就不支持`

`没用过 tachiyomiJ2K，试下其他工具有没有相同的问题，比如 https://github.com/mihonapp/mihon`

其实这个软件现在叫mihon（有很多不同的分支，都大同小异，我测试后问题表现一致），在里面装上Komga插件后可以连接komga服务器，方便离线使用环境。

epub格式，mihon是支持的，因为我今天重新下载了“干净的”资源并使用脚本搜刮后，并没有出现该问题（问题暂未复现），我的这些文件可能因为“历史悠久”，经过很多不同的软件（emby perfectview等等）处理过，出现了一些奇奇怪怪的BUG。

我现在如果想复现这个bug，只要导入旧的那些文件就会出现，但是新下载的“干净”文件暂时是正常的，搜刮后也是可以正常识别的。

由于新下载的文件可以正常搜刮，也许这个问题是那些文件不能正确被mihon处理把。

**Comment by chu-shen** [comment]
> 
> 由于新下载的文件可以正常搜刮，也许这个问题是那些文件不能正确被mihon处理把。

没问题就行👍
